# Generated by Django 5.2.6 on 2025-11-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recetasmedicas',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='medicamentos.profileuser'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='edad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recetasmedicas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetasmedicas', to='medicamentos.profileuser'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='alimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='medicamentos.alimentos'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
