# Generated by Django 5.2.8 on 2025-11-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_remove_notificaciones_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='telefono',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='roles',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Ususario'), ('premium', 'Usuario Premium'), ('usuario_secundario', 'Usuario Secundario')], default='user', max_length=20),
        ),
    ]
