# Generated by Django 5.2.8 on 2025-11-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_profileuser_telefono_alter_profileuser_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='edad',
            new_name='date_birth',
        ),
    ]
