# Generated by Django 5.2.6 on 2025-11-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_rename_edad_profileuser_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='pais',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
