# Generated by Django 5.2.8 on 2025-11-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0005_profileuser_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_user', to='medicamentos.profileuser'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='alimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_alimento', to='medicamentos.alimentos'),
        ),
    ]
