# Generated by Django 5.2.6 on 2025-11-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0007_medicamentosprogramados"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="medicamentosprogramados",
            name="unique_med_fecha_user",
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medicamentosprogramados",
            unique_together={("nombre", "fecha", "user")},
        ),
    ]
