# Generated by Django 5.2.8 on 2025-12-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0008_remove_medicamentosprogramados_unique_med_fecha_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentosprogramados',
            name='tomadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicamentosprogramados',
            name='total_tomas',
            field=models.IntegerField(default=3),
        ),
    ]
