# Generated by Django 5.2.8 on 2025-12-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0008_remove_medicamentosprogramados_unique_med_fecha_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamentos',
            old_name='nombre_medicamento',
            new_name='medicamento',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='f_caducidad',
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='medicamentos.profileuser'),
        ),
    ]
