# Generated by Django 5.2.8 on 2025-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0009_rename_nombre_medicamento_medicamentos_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
