# Generated by Django 5.2.6 on 2025-12-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0009_medicamentosprogramados_tomadas_and_more'),
        ('medicamentos', '0010_alter_medicamentos_descripcion'),
    ]

    operations = [
    ]
