# Generated by Django 5.2.6 on 2025-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0012_alter_medicamentosprogramados_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentosprogramados',
            name='fecha',
            field=models.DateField(),
        ),
    ]
