# Generated by Django 5.2.6 on 2025-12-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0011_merge_20251204_1359'),
        ('medicamentos', '0013_alter_medicamentosprogramados_fecha'),
    ]

    operations = [
    ]
