# Generated by Django 5.2.6 on 2025-12-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0014_merge_20251204_1859'),
        ('medicamentos', '0014_merge_20251205_1458'),
    ]

    operations = [
    ]
