# Generated by Django 5.2.6 on 2025-12-08 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0015_merge_20251208_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexoedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.CreateModel(
            name='MedicamentosMasRegistrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('edad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.sexoedad')),
            ],
        ),
        migrations.CreateModel(
            name='BusquedasChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(max_length=100)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
                ('edad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.sexoedad')),
            ],
        ),
    ]
