# Generated by Django 5.2.8 on 2025-12-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0015_merge_20251208_2124"),
        ("medicamentos", "0016_sexoedad_alter_profileuser_genero_and_more"),
    ]

    operations = []
