# Generated by Django 5.2.6 on 2025-12-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0017_merge_20251210_1725'),
        ('medicamentos', '0017_merge_20251210_1726'),
        ('medicamentos', '0017_merge_20251210_1822'),
    ]

    operations = [
    ]
